- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo

  tasks:

  - name: install yum-config-manger
    yum:
      name: yum-utils
      state: present
  
  - name: add official HashiCorp Linux repository
    shell:
      cmd: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
  
  - name: install vault
    yum:
      name: vault
   
  - name: Create vault data directory
    file:
      path: /var/lib/vault/data
      state: directory
      recurse: true
      owner: vault
      group: vault
      mode: '0770'
  
  - name: create directory for configuration and tls 
    file:
      path: /etc/vault.d/
      state: directory
      owner: vault
      group: vault
      mode: '0770'

  - name: config file for running vault as a service
    copy:
      dest: /etc/vault.d/vault.hcl
      content: '
      listener "tcp" {

        address     = "127.0.0.1:8200"
        tls_disable = 1

      }

      storage "file" {

        path = "/var/lib/vault/data"
    
      }'
      owner: vault
      group: vault
      force: yes

  - name: install systemd
    copy:
      dest: /usr/lib/systemd/system/vault.service
      content: '
        [Unit]
        Description="HashiCorp Vault - A tool for managing secrets"
        Documentation=https://www.vaultproject.io/docs/
        Requires=network-online.target
        After=network-online.target
        ConditionFileNotEmpty=/etc/vault.d/vault.hcl

        StartLimitIntervalSec=60
        StartLimitBurst=3

        [Service]
        User=vault
        Group=vault
        LogLevel=info
        ProtectSystem=full
        ProtectHome=read-only
        PrivateTmp=yes
        PrivateDevices=yes
        SecureBits=keep-caps
        AmbientCapabilities=CAP_IPC_LOCK
        Capabilities=CAP_IPC_LOCK+ep
        CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
        NoNewPrivileges=yes
        ExecStart=/bin/vault server -config=/etc/vault.d/vault.hcl
        ExecReload=/bin/kill --signal HUP $MAINPID
        KillMode=process
        KillSignal=SIGINT
        Restart=on-failure
        RestartSec=5
        TimeoutStopSec=30
        StartLimitInterval=60
        StartLimitIntervalSec=60
        StartLimitBurst=3
        LimitNOFILE=65536
        LimitMEMLOCK=infinity

        [Install]
        WantedBy=multi-user.target
        '
      owner: vault
      group: vault
      force: yes   

  - name: Create vault user
    user:
      name: vault
      system: yes
      shell: /bin/false
      home: /etc/vault.d
      createhome: null
      append: yes

  - name: start vault service
    service:
      name: vault
      state: started