- name: Install Apache
  yum:
    name: httpd
    state: latest
   
- name: upload webpage
  copy:
    dest: "{{default_webpage_dest}}"
    src: "{{default_webpage_src}}"
  when: upload == true

- name: Install EPEL 7
  yum_repository:
    name: epel
    description: Epel Repository
    file: epel
    baseurl: "{{epel_release_url}}"
    gpgcheck: yes
    gpgkey: "{{epel_key_url}}"
    enabled: yes

- name: Install dependencies
  yum:
    name: ['unzip', 'jq', 'awscli', 'ansible', 'python2-boto3', 'htop', 'git']
    state: present
    update_cache: true